.gitignore
CHANGELOG.md
package-lock.json
package.json
src/common/configuration.ts

* added managed.classPath setting
* deprecated managed.jarFile setting
Closes #39

ClassPath Setting

---

CHANGELOG.md
src/linter/linter.ts
src/test-fixtures/workspace/markdown/backticks.json
src/test-fixtures/workspace/markdown/basic.json
src/test-fixtures/workspace/markdown/basic.md
src/test-fixtures/workspace/markdown/front-matter.json
src/test-fixtures/workspace/markdown/front-matter.md
src/test-fixtures/workspace/markdown/headers.json
src/test/suite/linter.markdown.test.ts
src/test/suite/linter.test.ts

Reduced header marks to prevent inclusion of front matter.

Header Marks

---

.codacy.yml
.editorconfig
.vscode/settings.json
CHANGELOG.md
src/common/configuration-manager.ts
src/common/constants.ts
src/extension.ts
src/linter/linter.ts
src/test/runTest.ts
src/test/suite/configuration.test.ts
src/test/suite/extension.test.ts
src/test/suite/index.ts
src/test/suite/linter.markdown.test.ts
src/test/suite/linter.test.ts
src/typeFormatters/dashesFormatter.ts
src/typeFormatters/dispatcher.ts
src/typeFormatters/ellipsesFormatter.ts
src/typeFormatters/quotesFormatter.ts
tslint.json
webpack.config.ts

Cleaned up code inconsistencies / linter warnings.

Code cleanup

---

CHANGELOG.md
package-lock.json
package.json
src/common/configuration-manager.ts
src/extension.ts
src/linter/linter.ts
src/test-fixtures/workspace/.vscode/settings.json
tslint.json

* Lint on Save
* Lint on Open
* Diagnostic Severity

Linter options

---

CHANGELOG.md
package.json
src/common/configuration-manager.ts
src/test-fixtures/workspace/.vscode/settings.json

Managed ports

---

CHANGELOG.md
src/typeFormatters/quotesFormatter.ts

Smart Double Quotes Conditions

---

.prettierrc
package-lock.json
package.json
src/linter/linter.ts

use node-fetch instead of request-promise-native

---

CHANGELOG.md
package-lock.json
package.json
src/configuration/constants.ts
src/configuration/manager.ts
src/linter/linter.ts
src/test-fixtures/workspace/.vscode/settings.json

Feature - Hide Rule IDs

---

CHANGELOG.md
src/linter/linter.ts
src/test-fixtures/workspace/markdown/smart-format-formatted.md
src/test-fixtures/workspace/markdown/smart-format-unformatted.json
src/test-fixtures/workspace/markdown/smart-format-unformatted.md
src/test/suite/linter.test.ts

Apostrophes were being replaced by open single quote instead of close single quote. Closes #216

Smart Apostrophe

---

CHANGELOG.md
package.json
src/configuration/manager.ts
src/test-fixtures/workspace/.vscode/settings.json

Show the user a warning if Disabled Rules and/or Disabled Categories contain spaces. Closes #217

Disabled Rules and Categories

---

package-lock.json
package.json

node-fetch 2.6.6

---

.github/dependabot.yml
.github/workflows/codeql-analysis.yml
.github/workflows/dependabot-batcher.yaml
.github/workflows/nodejs-ci-push.yml
.github/workflows/nodejs-ci.yml
.github/workflows/vsce-publish.yml

Added:
* dependabot batcher
Updated:
* set node versions to `lts/*`

chore: dependabot automation and node version updates

---

.github/workflows/codeql-analysis.yml
.github/workflows/vsce-publish.yml
package-lock.json
package.json

This PR was created by the [Dependabot Batcher](https://github.com/Legal-and-General/dependabot-batcher) Action by combining the following PRs:
**Tue Dec 06 2022**
- #513
- #512
- #511
- #509
- #508
- #507
- #496

chore(deps): dependabot batch updates

---

README.md

`LanguageTool Linter > Managed: Jar File` => `LanguageTool Linter > Managed: Class Path`

chore: update option name in readme to be up to date

---

README.md

cf. https://github.com/badges/shields/issues/8671

doc: fix CI badge

---

README.md

Update URL for the languageserver wiki

doc: update url for the language server wiki

---

README.md

This page has been moved to  https://dev.languagetool.org/

docs: update redirect links in README.md

---

.vscode/launch.json
package.json
src/ConfigurationManager.ts
src/Constants.ts
test-fixtures/workspace/.vscode/settings.json
test/suite/extension.test.ts

feat: enable picky mode

---

package.json

fix: remove legacy "enabled" configuration item

---

package.json
src/ConfigurationManager.ts
src/Constants.ts
src/Linter.ts
src/StatusBarManager.ts
src/extension.ts

feat: add toggle suspend linting
